require 'nokogiri'
require 'logger'
require 'rake/clean'
require '../tools/multiio.rb'

STRON_SCHEMA = "../convml_11.sch"
STRON_COMPILED = "convml_11_sch-compiled.xsl"
XSD_SCHEMA = "../convml_11.xsd"

CLEAN.include('*.svrl')
CLEAN.include('*.log')
CLEAN.include(STRON_COMPILED)

FORMATTER = proc do |severity, datetime, progname, msg|
  "#{severity}: #{msg}\n"
end

log_file = File.open("test.log", "w")
LOG = Logger.new(MultiIO.new(log_file, STDOUT))
LOG.formatter = FORMATTER

ERR_LOG = Logger.new('fail.log')
ERR_LOG.formatter = FORMATTER

# Testowane pliki
XML_FILES = FileList['*.xml']
SVRL_FILES = XML_FILES.ext('svrl')

SVRL_FILES.each do |svrl|
  file svrl => [svrl.ext('xml'), STRON_COMPILED]
end

task :default => [:test]

task :test => [*SVRL_FILES] do
  err_count = 0
  
  # Testuje poprawne dokumenty
  XML_FILES.exclude("*Fail.xml").each do |f|
    err_count += validate f
  end
  
  # Testuje dokumenty z bledami
  Rake::FileList.new("*Fail.xml").each do |f|
    err_count += validate f, false
  end
  
  LOG.info
  if err_count == 0
    LOG.info "TEST SUCCESSFUL"
  else
    LOG.info "TEST FAILED!"
    LOG.info "#{err_count} errors"
  end
end

def validate(file, shouldBeValid=true)
  msg = "** validating #{file} **"
  LOG.info msg
  ERR_LOG.info msg

  errors = xsd_validate file, XSD_SCHEMA
  errors += stron_validate file
  errors.each {|e| ERR_LOG.info e }

  if errors.any? && shouldBeValid   
    errors.each {|e| LOG.fatal e }
    LOG.warn "#{errors.size} errors in #{file}"
    return errors.size
  elsif errors.empty? && !shouldBeValid
    LOG.fatal "#{file} should not be valid!"
    return 1
  end
  return 0
end

def xsd_validate(file, schema)
  xsd = Nokogiri::XML::Schema(File.read(schema))
  doc = Nokogiri::XML(File.read(file))
  errors = xsd.validate(doc)  
end

def xpath2to1(doc, xpath, ns={'conv' => 'http://www.entertech.com.pl/convml'})
  xpath.gsub!(/\[namespace-uri\(\)='[^']*'\]/, '')
  xpath.gsub!('*', ns.keys.first)
  doc.xpath(xpath, ns)
end

def rule_hints(results_doc, instance_doc, rule_type)
  results = []

  results_doc.xpath("//svrl:#{rule_type}").each do |hit|
    context = xpath2to1(instance_doc, hit['location']).first
    
    hit.xpath('svrl:text/text()').each do |message|
      results << {
        :rule_type => rule_type,
        #:type => context.node_type_name,
        :name => context.name,
        :line => context.line,
        :message => message.content.strip }
    end
  end
  results  
end

def stron_validate(file)
  report_file = file.ext('svrl') 
  doc = Nokogiri::XML(File.read(file))
  report = Nokogiri::XML(File.read(report_file))

  rule_hints(report, doc, 'successful-report').each {|r| LOG.info r}
  errors = rule_hints(report, doc, 'failed-assert')
end

file STRON_COMPILED => [STRON_SCHEMA] do
  schema_file = STRON_SCHEMA
  stron_file = "../thirdparty/iso-schematron-xslt2/iso_svrl_for_xslt2.xsl"
  output_file = STRON_COMPILED

  LOG.info "compiling #{schema_file}"
  xslt2_transform(stron_file, schema_file, output_file)
end

def xslt2_transform(xsl_file, in_file, out_file)
  saxon_jar = "../thirdparty/saxon9he.jar"
  flag = "" #"-t"
  sh "java -cp #{saxon_jar} net.sf.saxon.Transform #{flag} -s:#{in_file} -xsl:#{xsl_file} -o:#{out_file}"
end

rule '.svrl' => '.xml' do |t|
  xslt2_transform STRON_COMPILED, t.source, t.name
end
