require 'nokogiri'
require 'logger'
require './multiio.rb'

File.delete("test.log") if File.exists?("test.log")
log_file = File.open("test.log", "w")
@@log = Logger.new(MultiIO.new(log_file, STDOUT))
@@log.formatter = proc do |severity, datetime, progmane, msg|
  "#{severity}: #{msg}\n"
end

task :default => [:test]

task :test do
  # Test szablonu
  validate "../convml_11_template.xml"
  
  # Testuje poprawne dokumenty
  Rake::FileList.new("*.xml").exclude("*Fail.xml").each do |f|
    validate f
  end
  
  # Testuje dokumenty z bledami
  Rake::FileList.new("*Fail.xml").each do |f|
    validate f, false
  end
end

task :stron => ["convml_11_sch-compiled.xsl"] do
  schematron "../convml_11_template.xml"

  Rake::FileList.new("*.xml").each do |f|
    schematron f
  end  
end


def validate(file, shouldBeValid=true)
  schema = "../convml_11.xsd"
  validateWithRuby schema, file, shouldBeValid
end

def validateWithRuby(schema, file, shouldBeValid=true)
  @@log.info "validating #{file}"
  xsd = Nokogiri::XML::Schema(File.read(schema))
  doc = Nokogiri::XML(File.read(file))
  errors = xsd.validate(doc)
  
  if errors.any? && shouldBeValid   
    errors.each {|e| @@log.fatal e }
    @@log.warn "#{errors.size} errors in #{file}"
  elsif errors.empty? && !shouldBeValid
    @@log.fatal "#{file} should not be valid!"
  end
end

def rule_hints(results_doc, instance_doc)
  results = []
  rule_type = 'failed-assert'

  results_doc.xpath("//svrl:#{rule_type}").each do |hit|
    context = instance_doc.xpath(hit['location']).first
    
    hit.xpath('svrl:text/text()').each do |message|
      results << {
        :rule_type => rule_type,
        #:type => context.node_type_name,
        :name => context.name,
        :line => context.line,
        :message => message.content.strip }
    end
  end
  results  
end

def schematron(file, shouldBeValid=true)
  xsl = Nokogiri::XSLT(File.read('convml_11_sch-compiled.xsl'))
  doc = Nokogiri::XML(File.read(file))

  report = xsl.transform(doc)
  errors = rule_hints(report, doc)
  errors.each {|e| @@log.fatal e } 
end

file "convml_11_sch-compiled.xsl" => ["../convml_11.sch"] do
  @@log.info "compiling ../convml_11.sch"
  xsl = Nokogiri::XSLT(File.open('../ISO_Schematron/iso_svrl_for_xslt1.xsl', 'r'))
  doc = Nokogiri::XML(File.read('../convml_11.sch'))

  File.open("convml_11_sch-compiled.xsl", "w") do |f|
    f.puts xsl.transform(doc)
  end
end

