task :default => :pdf

task :pdf => ["convml.tex"] do
  sh "pdflatex convml.tex"
end

task :html do
     sh "plastex --toc-non-files convml.tex"
     sh <<CMD
for f in convml/images/*.png
do
  convert -verbose -resize '700X700>' $f $f
done
CMD
end

task :deploy => [:pdf, :html] do
  target = "entertech@entertech.com.pl:~/public_html"
  source = "convml"

  sh "cp convml.pdf convml/"
  sh "cp ../convml_11.xsd convml/"
  sh <<CMD
scp -r #{source} #{target}
CMD
end

task :clean do
  sh "rm *.toc *.aux *.paux *.out *.log"
  sh "rm convml.pdf"
  sh "rm -R convml"
end
